spring.application.name=winter-snack
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#view resolver
spring.mvc.view.prefix=/WEB-INF/views/contents/
spring.mvc.view.suffix=.jsp
spring.mvc.view.encoding=UTF-8
spring.mvc.static-path-pattern=/static/**
spring.mvc.view.cache=false

#mapper
mybatis.mapper-locations=classpath:mapper/xml/**/*.xml
mybatis.type-aliases-package=jsj.store.winter_snack.dto
mybatis.configuration.map-underscore-to-camel-case=true

#dbms
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=WS
spring.datasource.password=1234
logging.level.org.mybatis=TRACE
logging.level.com.yourapp.mapper=TRACE
logging.level.org.apache.ibatis=DEBUG
logging.level.org.mybatis.spring=DEBUG

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl



