spring.application.name=winter-snack
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#view resolver
spring.mvc.view.prefix=/WEB-INF/views/contents/
spring.mvc.view.suffix=.jsp
spring.mvc.view.encoding=UTF-8
spring.mvc.static-path-pattern=/static/**
spring.mvc.view.cache=false

#mapper
mybatis.mapper-locations=classpath:mapper/xml/**/*.xml
mybatis.type-aliases-package=jsj.store.winter_snack.dto

#dbms
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=WS
spring.datasource.password=1234
logging.level.org.mybatis=DEBUG
logging.level.com.yourapp.mapper=DEBUG
logging.level.org.apache.ibatis=DEBUG
logging.level.org.mybatis.spring=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl



